baseurl = "https://hammashamzah.com/"
title = "Hammas Hamzah's Blog"
copyright = "Copyright &copy; 2017 - Hammas Hamzah Kuddah"
canonifyurls = true

theme = "kiera"

disqusShortname = "hammashamzah"
googleAnalytics = "UA-115647532-1"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
  name = "Hammas Hamzah Kuddah"
  email = "hammas.hamzah@gmail.com"
  github = "hammashamzah"
  linkedin = "hammashamzah"
  twitter = "hammashamzah"

[params]
    tagline = "Some things are better left written"